engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:
          mass_threshold: 91
  eslint:
    enabled: true
    channel: "eslint-2"
  fixme:
    enabled: true
  flog:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-58
  scss-lint:
    enabled: true
ratings:
  paths:

  - "**.erb"
  - "**.rb"
  - "**.css"
  - "**.scss"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - config/initializers/**/*
exclude_paths:
- config/
- db/
- node_modules/
- spec/
- test/
- vendor/
- tmp/
- log/
- app/assets/javascripts/goldencobra/html_editors/**/*
- app/assets/javascripts/goldencobra/**.min.js
- app/assets/javascripts/goldencobra/chosen.jquery.js
- app/assets/javascripts/goldencobra/chosen.jquery.min.js
- app/assets/javascripts/goldencobra/countable.js
- app/assets/javascripts/goldencobra/jquery.*
- app/assets/javascripts/goldencobra/keymaster.js
- app/assets/javascripts/goldencobra/moment.js
- app/assets/javascripts/goldencobra/tiny_mce*.js
- app/assets/javascripts/goldencobra/togetherjs.js
- doc/
- Gemfile.lock
- .rubocop.yml
- .codeclimate.yml
- .scss-lint.yml
- .eslintrc
- .csslintrc

