goldencobra:
  locations:
    geocoding: "false"
  live-support:
    active: "false"
    email: "metz@ikusei.de"
  translations:
    use_db_store: "false"
  analytics:
    active: "false"
    timespan_in_days: "360"
  bugherd:
    user: "current_user"
    role: "admin"
    api: ""
  comments:
    commentator: "User"
  menues:
    recreate_cache: "false"
  widgets:
    recreate_cache: "false"
    time_control: "true"
  html2pdf_uid: "c5c13af822"
  use_solr: "false"
  page:
    default_title_tag: ""
    default_meta_description_tag: ""
  article:
    preview:
      roles: "Admin"
    edit_link:
      user: "current_user"
      role: "admin"
    image_positions: "standard"
    cache_articles: "false"
    max_cache_24h: "false"
    article_index:
      link_to_article: "weiterlesen"
  use_ssl: "false"
  url: ""
  facebook:
    appid: ""
    opengraph_default_image: ""
  geocode_ip_address: "false"
  remove_old_versions:
    active: "true"
    weeks: "2"
  visitors:
    send_confirmation_email: "false"
  upload:
    convert_options: "-strip -colorspace sRGB -flatten"
  random_logo_url: ""
  backend:
    index:
      download_links: "true"
